Bring latest azure pipeline changes to package
- make testing configurable
- be able to release to production
- fix typos in filenames

diff --git a/cicd/laravel/.cicd/azure-pipelines-stages--Release_Production.yml b/cicd/laravel/.cicd/azure-pipelines-stages--Release_Production.yml
--- a/cicd/laravel/.cicd/azure-pipelines-stages--Release_Production.yml
+++ b/cicd/laravel/.cicd/azure-pipelines-stages--Release_Production.yml
@@ -38,9 +38,99 @@ stages:
                   echo "app_maintenance_during_deployment_enabled__stage_production = '$(app_maintenance_during_deployment_enabled__stage_production)'"
                 displayName: 'DEBUG'
                 condition: eq(variables['debug_mode__stage_production_deployment'], true)
+              # //////////////////////////////////////////////////////////////////////
+              # // Preparation
+
+              - task: InstallSSHKey@0
+                inputs:
+                  knownHostsEntry: $(PRODUCTION_ENV_SSH_KNOWN_HOST_ENTRY)
+                  sshPublicKey: $(ARTIFACT_REPOSITORY_SSH_PUBLIC_KEY)
+                  sshKeySecureFile: $(ARTIFACT_REPOSITORY_SSH_KEY_SECURE_FILENAME)
+                displayName: 'Preparation: install ssh key'
 
               - bash: |
-                  echo -e "Deployment: Placeholder (version: '$(artifactVersionBuildTagFromBuild)')"
-                  echo -e 'NOT IMPLEMENTED'
-                  exit 1
-                displayName: 'Deployment: Placeholder'
+                  ssh $(PRODUCTION_ENV_SSH_URL) << SSH_COMMAND
+                    cd $(PRODUCTION_ENV_APP_PATH)
+                    pwd
+                    git fetch --all --tags
+                  SSH_COMMAND
+                displayName: 'Preparation: fetch current artifacts repository'
+
+              - bash: |
+                  ssh $(PRODUCTION_ENV_SSH_URL) << SSH_COMMAND
+                    cd $(PRODUCTION_ENV_APP_PATH)
+                    php artisan down --render="errors::503" --retry=60
+                  SSH_COMMAND
+                displayName: 'Preparation: set application into maintenance'
+                condition: and(succeeded(), eq(variables['app_maintenance_during_deployment_enabled__stage_production'], true))
+
+              - bash: |
+                  ssh $(PRODUCTION_ENV_SSH_URL) << SSH_COMMAND
+                    cd $(PRODUCTION_ENV_APP_PATH)
+                    php artisan backup:run --only-db --no-interaction --timeout=120
+                  SSH_COMMAND
+                displayName: 'Preparation: backup db'
+                condition: and(succeeded(), eq(variables['db_backup_enabled__stage_production'], true))
+
+              # //////////////////////////////////////////////////////////////////////
+              # // Deployment
+
+              - bash: |
+                  current_artifact_version='$(artifactVersionBuildTagFromBuild)'
+                  ssh $(PRODUCTION_ENV_SSH_URL) << SSH_COMMAND
+                    cd $(PRODUCTION_ENV_APP_PATH)
+                    echo ''
+                    if [[ -z "${current_artifact_version}" ]]; then
+                      echo -e "ERROR: '\$current_artifact_version' is not defined"
+                      exit 1
+                    fi
+                    echo ''
+                    echo -e "INFO:  Current Artifact Version: '${current_artifact_version}'"
+                    echo ''
+                    git checkout "${current_artifact_version}"
+                    git status
+                    git --no-pager log -1
+                  SSH_COMMAND
+                displayName: 'Deployment: install new version'
+
+              - bash: |
+                  ssh $(PRODUCTION_ENV_SSH_URL) << SSH_COMMAND
+                    cd $(PRODUCTION_ENV_APP_PATH)
+                    php artisan migrate --force
+                  SSH_COMMAND
+                displayName: 'Deployment: migrate database'
+                condition: and(succeeded(), eq(variables['db_migration_enabled__stages_release'], true))
+
+              - bash: |
+                  ssh $(PRODUCTION_ENV_SSH_URL) << SSH_COMMAND
+                    cd $(PRODUCTION_ENV_APP_PATH)
+                    php artisan storage:link --relative
+                  SSH_COMMAND
+                displayName: 'Deployment: link storage'
+
+              - bash: |
+                  ssh $(PRODUCTION_ENV_SSH_URL) << SSH_COMMAND
+                    cd $(PRODUCTION_ENV_APP_PATH)
+                    php artisan up
+                  SSH_COMMAND
+                displayName: 'Deployment: bootup application'
+
+              - bash: |
+                  ssh $(PRODUCTION_ENV_SSH_URL) << SSH_COMMAND
+                  (
+                    flock -w 10 9 || exit 1
+                    echo 'Restarting FPM...';
+                    sudo /usr/sbin/service php7.4-fpm reload
+                  ) 9>/tmp/fpmlock
+                  SSH_COMMAND
+                displayName: 'Deployment: restart php fpm for opcache invalidation'
+
+              # //////////////////////////////////////////////////////////////////////
+              # // Test
+
+              - bash: |
+                  curl -fsSL "${PRODUCTION_ENV_URL}"
+                displayName: 'Test: is application up and running'
+
+
+
