Fix broken xdebug container switch

diff --git a/src/commands/docker-exec-xdebug b/src/commands/docker-exec-xdebug
--- a/src/commands/docker-exec-xdebug
+++ b/src/commands/docker-exec-xdebug
@@ -1,82 +1,45 @@
 #!/usr/bin/env bash
 
 # NOTE: At the moment, this has only been confirmed to work with PHP 7
-
-
 # Grab full name of php-fpm container
-PHP_FPM_CONTAINER=$(docker ps | grep php-fpm | awk '{print $1}')
+PHP_FPM_CONTAINER_NAME="${PHP_FPM_CONTAINER_NAME:-php-fpm}"
+PHP_FPM_CONTAINER_ID="$(docker ps | grep "${PHP_FPM_CONTAINER_NAME}" | awk '{print $1}')"
 
-
-# Grab OS type
-if [[ "$(uname)" == "Darwin" ]]; then
-    OS_TYPE="OSX"
-else
-    OS_TYPE=$(expr substr $(uname -s) 1 5)
+if [[ -z "${PHP_FPM_CONTAINER_ID}" ]]; then
+  echo "ERROR: Container '${PHP_FPM_CONTAINER_NAME}' is not running, please start it"
+  echo ''
+  exit 1
 fi
 
-
-xdebug_status ()
-{
-    echo 'xDebug status'
-
-    # If running on Windows, need to prepend with winpty :(
-    if [[ $OS_TYPE == "MINGW" ]]; then
-        winpty docker exec -it $PHP_FPM_CONTAINER bash -c 'php -v'
-    else
-        docker exec -it $PHP_FPM_CONTAINER bash -c 'php -v'
-    fi
-
+xdebug_status () {
+    echo "INFO:  xDebug status: '${PHP_FPM_CONTAINER_NAME}' container with '${PHP_FPM_CONTAINER_ID}' id"
+    echo ''
+    docker exec -it "${PHP_FPM_CONTAINER_ID}" bash -c 'php -v'
 }
 
-
-xdebug_start ()
-{
-    echo 'Start xDebug'
-
+xdebug_start () {
+    echo "INFO:  Start xDebug: '${PHP_FPM_CONTAINER_NAME}' container with '${PHP_FPM_CONTAINER_ID}' id"
+    echo ''
     # And uncomment line with xdebug extension, thus enabling it
     ON_CMD="sed -i 's/^;zend_extension=/zend_extension=/g' \
                     /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
 
-    # If running on Windows, need to prepend with winpty :(
-    if [[ $OS_TYPE == "MINGW" ]]; then
-        winpty docker exec -it $PHP_FPM_CONTAINER bash -c "${ON_CMD}"
-        docker restart $PHP_FPM_CONTAINER
-        winpty docker exec -it $PHP_FPM_CONTAINER bash -c 'php -v'
-
-    else
-        docker exec -it $PHP_FPM_CONTAINER bash -c "${ON_CMD}"
-        docker restart $PHP_FPM_CONTAINER
-        docker exec -it $PHP_FPM_CONTAINER bash -c 'php -v'
-    fi
+    docker exec -it "${PHP_FPM_CONTAINER_ID}" bash -c "${ON_CMD}"
+    docker restart "${PHP_FPM_CONTAINER_ID}"
+    docker exec -it "${PHP_FPM_CONTAINER_ID}" bash -c 'php -v'
 }
 
-
-xdebug_stop ()
-{
-    echo 'Stop xDebug'
-
+xdebug_stop () {
+    echo "INFO:  Stop xDebug: '${PHP_FPM_CONTAINER_NAME}' container with '${PHP_FPM_CONTAINER_ID}' id"
+    echo ''
     # Comment out xdebug extension line
     OFF_CMD="sed -i 's/^zend_extension=/;zend_extension=/g' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
 
-
-    # If running on Windows, need to prepend with winpty :(
-    if [[ $OS_TYPE == "MINGW" ]]; then
-        # This is the equivalent of:
-        # winpty docker exec -it laradock_php-fpm_1 bash -c 'bla bla bla'
-        # Thanks to @michaelarnauts at https://github.com/docker/compose/issues/593
-        winpty docker exec -it $PHP_FPM_CONTAINER bash -c "${OFF_CMD}"
-        docker restart $PHP_FPM_CONTAINER
-        #docker-compose restart php-fpm
-        winpty docker exec -it $PHP_FPM_CONTAINER bash -c 'php -v'
-
-    else
-        docker exec -it $PHP_FPM_CONTAINER bash -c "${OFF_CMD}"
-        # docker-compose restart php-fpm
-        docker restart $PHP_FPM_CONTAINER
-        docker exec -it $PHP_FPM_CONTAINER bash -c 'php -v'
-    fi
+    docker exec -it "${PHP_FPM_CONTAINER_ID}" bash -c "${OFF_CMD}"
+    # docker-compose restart php-fpm
+    docker restart "${PHP_FPM_CONTAINER_ID}"
+    docker exec -it "${PHP_FPM_CONTAINER_ID}" bash -c 'php -v'
 }
-
 
 case $@ in
     stop|STOP)
@@ -88,11 +51,8 @@ case $@ in
     status|STATUS)
         xdebug_status
         ;;
-    *)
-        echo "xDebug [Stop | Start | Status] in the ${PHP_FPM_CONTAINER} container."
-        echo "xDebug must have already been installed."
-        echo "Usage:"
-        echo "  .php-fpm/xdebug stop|start|status"
+    help|*)
+        echo "USAGE: cmd [stop|start|status]"
+        echo "       for starting '${PHP_FPM_CONTAINER_NAME}' container with '${$PHP_FPM_CONTAINER_ID}' id"
         exit 1
-
 esac
